Repository fusionjs/fusion-plugin-rpc, pull requests merged in 2018-11, with the labels that each got.

#190 Add getMockRpcHandlers util and tests
  .gitignore
  README.md
  package.json
  src/__tests__/test-mock-rpc-handlers.browser.js
  src/index.js
  src/mock-rpc-handlers.js
  yarn.lock
Labels: feature

#192 Release v2.2.0
  package.json
Labels: release

#193 Export types
  package.json
  src/index.js
  yarn.lock
Labels: feature

#194 Release v2.3.0-0
  package.json
Labels: release

#195 Release v2.3.0
  package.json
Labels: release

#197 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
