Repository fusionjs/fusion-plugin-rpc, pull requests merged in 2018-10, with the labels that each got.

#180 Release v2.1.3
  package.json
Labels: release

#182 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#188 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor
