Repository fusionjs/fusion-plugin-rpc, pull requests merged in 2019-02, with the labels that each got.

#209 Release v2.3.1-0
  package.json
Labels: release

#211 Release v2.3.1
  package.json
Labels: release

#213 Update error message to have more information
  src/__tests__/index.node.js
  src/server.js
Labels: feature

#214 Remove unused dependency
  package.json
  yarn.lock
Labels: refactor

#215 Release v2.4.0-0
  package.json
Labels: release

#217 Release v2.4.0
  package.json
Labels: release

#218 Replace lodash.isEqual with just-compare
  package.json
  src/mock-rpc-handlers.js
  yarn.lock
Labels: refactor
